Updated the customer profile API and UX
hs2361/horario pull request #10
Opened 2021-10-09 10:41 UTC by AlecsisDuarte

Included the Bio and Birthday of the customer as optional fields into the Sign Up & Profile screens

2021-10-09 10:41 UTC, AlecsisDuarte commented
Addresses issue #10

2021-10-09 10:44 UTC, AlecsisDuarte commented
@DebadityaPal - Sorry for the long commit. I tried to avoid having to make several changes, but as I was going I noticed I was repeating a lot of code hence, updated several workflows.

Let me know what do you think

2021-10-09 11:15 UTC, hs2361 commented
Hello @AlecsisDuarte. Thanks a lot for your PR! We really appreciate you taking the time to contribute to the project. I'll take a look through your changes and ask for clarifications if needed.

2021-10-09 11:48 UTC, DebadityaPal commented
Hey @AlecsisDuarte , this is amazing work! Thanks a lot for your PR!

2021-10-09 12:23 UTC, hs2361 requested changes

2021-10-09 12:23 UTC, hs2361 commented on lib/screens/profile_screen.dart
> +      _nameInputController.text = user.name!;
I understand the rationale behind using a null check operator here, since we were enforcing the name to be non-null during sign up. However, earlier we were using Firebase Auth to get the user's name. Now, in your version, you're using Firestore to get the user's name instead of Firebase Auth. While this works for new users, for existing users who will be upgrading to the new version of the app there will be no value for "name" in Firestore (since the name was stored in Firebase Auth for them). This causes the app to crash since we are using a null check operator on a null value. Instead of this, we should use
```dart
_nameInputController.text = user.name ?? "";
```

2021-10-09 12:23 UTC, hs2361 commented on lib/widgets/sign_up_form.dart
> +  Widget _getSingUpButton() => _isLoading
Please rename the function to `_getSignUpButton`

2021-10-09 12:23 UTC, hs2361 commented on lib/widgets/sign_up_form.dart
> +          "We have just sent you a verification email. Please verify your email before and then sign in");
This sentence could be better framed as "Please verify your email before signing in"

2021-10-09 12:23 UTC, hs2361 commented on pubspec.yaml
> +  flutter_colorpicker: ^0.5.0
Why is this dependency override required? We are using `flutter_colorpicker` version ^0.6.0 already. Is there a specific reason why you're using ^0.5.0?

2021-10-09 12:30 UTC, hs2361 commented
@AlecsisDuarte Apart from these changes, I also had a couple of suggestions for your PR -
* We already have a widgets directory for any custom widgets that we use. Please move all the files inside of the `components` directory into the `widgets` directory.
* Why is there an additional `UserService` provider? All of the actions that the UserService provider performs can be included as additional getters inside of the existing `AuthService` provider. In other words, we should add more getters to the `AuthService` provider instead of creating a new provider.

Overall, your PR looks great! I just had a few suggestions and changes, and it'd be great if you could implement them.

2021-10-15 04:14 UTC, AlecsisDuarte commented on lib/screens/profile_screen.dart
> +      _nameInputController.text = user.name!;
Good catch, do you recommend we keep using firebaseAuth approach? I'm leaning more towards the new User profile, and simply leave firebaseAuth for password and email information to properly separate critical information form more non-critical.

I'll fetch FirebaseAuth's username in case the Firestore entity doesn't have it.

2021-10-15 04:14 UTC, AlecsisDuarte commented on lib/widgets/sign_up_form.dart
> +  Widget _getSingUpButton() => _isLoading
I always tend to make this mistake, thank you!!

2021-10-15 04:15 UTC, AlecsisDuarte commented on lib/widgets/sign_up_form.dart
> +          "We have just sent you a verification email. Please verify your email before and then sign in");
Totally, I was planning to reduce it as well, but decided to reduce the scope of my changes given that they were already too big.

I'll make sure to refactor this one too.

2021-10-15 04:16 UTC, AlecsisDuarte commented on pubspec.yaml
> +  flutter_colorpicker: ^0.5.0
Whut? Don't know why my editor did that (I guess I overrode a change right before mine. 
I'll refactor

2021-10-15 04:19 UTC, AlecsisDuarte commented
Thank you very much for the feedback!

I totally missed the widgets directory.

I would still advice into separating the logic between login and customer info.
This way as AuthService logic increases, say to add another sign-in form (e.g., LoginWithGoogle) it would make such class too big and same goes for the customer data in case you ever want to add more logic/data into it, it will keep increasing, but overall, I think that would be thinking too much into the future and thus, having everything under the same class (AuthService) seems the most feasible approach as of now.

2021-10-18 12:30 UTC, hs2361 commented on lib/screens/profile_screen.dart
> +      _nameInputController.text = user.name!;
@AlecsisDuarte Sure, if you can implement that functionality that would be great.

2021-10-18 12:53 UTC, hs2361 requested changes

2021-10-18 12:53 UTC, hs2361 commented on pubspec.yaml
> +  flutter_colorpicker: ^0.6.0
Could you remove the dependency override entirely, since we're using ^0.6.0 anyway? It will create warnings while running `flutter pub get`.

2021-10-18 12:58 UTC, hs2361 commented
@AlecsisDuarte Thanks for working on all the suggestions! I'll merge your PR once the dependency override is removed. I had another idea, which would make having the birthday information more useful - maybe we could show a notification at 00:00 on the user's birthday? We're already using the `flutter_local_notifications` package, so scheduling the notification after sign up shouldn't be too complicated. Feel free to create an issue about this if you could work on this. If you have any other ideas, do let us know! We'd love to hear them.

2021-10-19 06:27 UTC, AlecsisDuarte commented on lib/screens/profile_screen.dart
> +      _nameInputController.text = user.name!;
Yes, this was included in the latest commit

2021-10-19 06:27 UTC, AlecsisDuarte commented on pubspec.yaml
> +  flutter_colorpicker: ^0.6.0
Good catch, I still don't know why it got included on my code change 😅

Thanks!!

2021-10-19 06:28 UTC, AlecsisDuarte commented
> @AlecsisDuarte Thanks for working on all the suggestions! I'll merge your PR once the dependency override is removed. I had another idea, which would make having the birthday information more useful - maybe we could show a notification at 00:00 on the user's birthday? We're already using the `flutter_local_notifications` package, so scheduling the notification after sign up shouldn't be too complicated. Feel free to create an issue about this if you could work on this. If you have any other ideas, do let us know! We'd love to hear them.

@hs2361 - That is a really good idea! I will create the issue, although I'm not sure if I'll have enough time to pick it up 😢

2021-10-20 05:49 UTC, hs2361 approved these changes
Thanks for making the requested changes, @AlecsisDuarte. We really appreciate you taking the time to contribute to Horario!

2021-10-20 05:50 UTC, merged

2021-10-20 16:48 UTC, AlecsisDuarte commented
Glad to help and thank you for the prompt feedback!